#!/usr/bin/env python3
"""
小MiMo cookie 持久化助手 — 本机 Chrome 弹出控制台入口 → 你手动登入过米验证 → 自动抓 cookie 推送服务器
与 minimax_cookie_push 共享 cookie_push 端点
"""
import sys, time, json, urllib.request, urllib.error
from urllib.parse import quote

sys.stdout.reconfigure(encoding='utf-8')

SERVER = "https://ait.ll264a.cn"
PLATFORM = "xiaomi"   # DB 平台 key
DOMAIN = ".xiaomimimo.com"  # 抓哪些域名的 cookie
ENTRY_URL = "https://platform.xiaomimimo.com/console/plan-manage"
TIMEOUT_MIN = 10   # 最多等 10 分钟

def log(msg):
    print(f"[{time.strftime('%H:%M:%S')}] {msg}", flush=True)

def to_netscape(cookies):
    """CDP 抓到的 cookie 列表 → Netscape 格式字符串"""
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by mimo_wait_login.py",
        "# Platform: xiaomi (MiMo)",
        "",
    ]
    for c in cookies:
        domain = c.get("domain", "")
        flag = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure") else "FALSE"
        expiry = c.get("expires")
        if expiry is None or expiry < 0:
            expiry = int(time.time()) + 86400 * 30
        expiry = int(expiry)
        name = c.get("name", "")
        value = c.get("value", "")
        lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{expiry}\t{name}\t{value}")
    return "\n".join(lines) + "\n"

def push_to_server(cookie_str):
    """调用现有 cookie_push 端点(同 minimax 通道), credential_type=cookie"""
    payload = json.dumps({
        "type": "cookie_push",
        "payload": {
            "platform": PLATFORM,
            "cookie": cookie_str,
        },
    }, ensure_ascii=False).encode("utf-8")
    req = urllib.request.Request(
        f"{SERVER}/receive.php",
        data=payload,
        headers={
            "Content-Type": "application/json",
            "X-Token": "tm_2026_change_me",
            "Host": "ait.ll264a.cn",
        },
    )
    try:
        resp = urllib.request.urlopen(req, timeout=15)
        body = resp.read().decode("utf-8")
        log(f"PUSH RESPONSE: {body[:200]}")
        return json.loads(body)
    except urllib.error.HTTPError as e:
        log(f"PUSH HTTP ERROR: {e.code} {e.reason}")
        try:
            log(f"BODY: {e.read().decode('utf-8')[:300]}")
        except Exception:
            pass
        return None
    except Exception as e:
        log(f"PUSH ERROR: {type(e).__name__}: {e}")
        return None

def main():
    from playwright.sync_api import sync_playwright
    log(">> 启动 Playwright 真 Chrome <<")
    log(f">> 入口: {ENTRY_URL}")
    log(">> 你需要：手动点密码登录 → 填账号密码 → 过米验证 → 等自动推送 <<")

    start = time.time()
    with sync_playwright() as p:
        browser = p.chromium.launch(
            headless=False,
            channel="chrome",
            args=[
                "--disable-blink-features=AutomationControlled",
                "--no-sandbox",
                "--disable-infobars",
            ],
        )
        ctx = browser.new_context(
            viewport={"width": 1280, "height": 900},
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        )
        # 真 Chrome 启动 + 不加 navigator.webdriver 抹除（避免触发风控）
        page = ctx.new_page()
        log(f">> goto {ENTRY_URL}")
        page.goto(ENTRY_URL, wait_until="domcontentloaded", timeout=30000)
        log(f">> 当前 URL: {page.url[:120]}")

        pushed = False
        while time.time() - start < TIMEOUT_MIN * 60:
            elapsed = int(time.time() - start)
            try:
                cookies = ctx.cookies()
                mimo = [c for c in cookies if DOMAIN in c.get("domain", "") or c.get("domain", "").endswith("xiaomimimo.com")]
                url = page.url
                on_login = "account.xiaomi.com" in url
                if mimo and not on_login:
                    log(f">> 已检测到 {len(mimo)} 个 MiMo cookie，URL 已离登录页")
                    cookie_str = to_netscape(mimo)
                    log(f">> cookie 长度: {len(cookie_str)}, 准备推送")
                    resp = push_to_server(cookie_str)
                    if resp and resp.get("status") == "ok":
                        log("✅ 推送成功! 你可以关闭浏览器了")
                        pushed = True
                        break
                    else:
                        log("⚠️ 推送失败, 60s 后重试")
                else:
                    if elapsed % 10 == 0:
                        log(f"   [{elapsed}s] 监控中... MiMo cookies={len(mimo)} on_login={on_login}")
            except Exception as e:
                log(f"监控异常: {type(e).__name__}: {e}")
            time.sleep(3)

        if not pushed:
            log(f"⚠️ 超时 ({TIMEOUT_MIN} 分钟), 未检测到登录成功")
        try:
            input("按回车关闭浏览器...")
        except EOFError:
            time.sleep(2)
        browser.close()

if __name__ == "__main__":
    main()