// TokenScope Chrome 插件 - 后台服务
const API_BASE = 'https://ait.ll264a.cn';

// ============ TOTP 生成 ============
// Base32 解码
function base32Decode(str) {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
  str = str.replace(/\s/g, '').toUpperCase();
  let bits = 0, bitLen = 0, bytes = [];
  for (let i = 0; i < str.length; i++) {
    const pos = chars.indexOf(str[i]);
    if (pos === -1) continue;
    bits = (bits << 5) | pos;
    bitLen += 5;
    if (bitLen >= 8) {
      bitLen -= 8;
      bytes.push((bits >> bitLen) & 0xff);
    }
  }
  return new Uint8Array(bytes);
}

// HMAC-SHA1
async function hmacSha1(key, data) {
  const cryptoKey = await crypto.subtle.importKey('raw', key, { name: 'HMAC', hash: 'SHA-1' }, false, ['sign']);
  return new Uint8Array(await crypto.subtle.sign('HMAC', cryptoKey, data));
}

// 生成 TOTP 6 位码
async function generateTotp(secret) {
  const key = base32Decode(secret);
  const counter = Math.floor(Date.now() / 30000);
  const buf = new ArrayBuffer(8);
  const view = new DataView(buf);
  view.setBigUint64(0, BigInt(counter), false);
  const hmac = await hmacSha1(key, new Uint8Array(buf));
  const offset = hmac[19] & 0xf;
  const code = ((hmac[offset] & 0x7f) << 24) | ((hmac[offset + 1] & 0xff) << 16) | ((hmac[offset + 2] & 0xff) << 8) | (hmac[offset + 3] & 0xff);
  return String(code % 1000000).padStart(6, '0');
}

// 带 TOTP 的 API 调用
async function apiWithTotp(method, path, body) {
  const { totpKeyName, totpSecret } = await chrome.storage.local.get(['totpKeyName', 'totpSecret']);
  if (!totpSecret) return { error: '请先设置 API 密钥' };
  const totpCode = await generateTotp(totpSecret);
  const headers = { 'Content-Type': 'application/json', 'X-TOTP-Key': totpKeyName || 'default', 'X-TOTP-Code': totpCode };
  const resp = await fetch(API_BASE + path, { method, headers, body: body ? JSON.stringify(body) : undefined });
  if (resp.status === 401) return { error: 'TOTP 验证失败，请检查密钥' };
  const data = await resp.json();
  if (!resp.ok) return { error: data.detail || data.error || `HTTP ${resp.status}` };
  return data;
}

// ============ Cookie 采集 ============
async function collectPlatform(platform, domain) {
  try {
    const cookies = await chrome.cookies.getAll({ domain });
    if (!cookies || cookies.length === 0) return { status: 'no_cookies', platform, count: 0 };
    const seen = new Set();
    const lines = [];
    for (const c of cookies) {
      const key = c.domain + c.name + c.path;
      if (seen.has(key)) continue;
      seen.add(key);
      lines.push(`${c.domain}\t${c.domain.startsWith('.') ? 'TRUE' : 'FALSE'}\t${c.path || '/'}\t${c.secure ? 'TRUE' : 'FALSE'}\t${Math.floor(c.expirationDate || (Date.now()/1000 + 86400*30))}\t${c.name}\t${c.value}`);
    }
    return {
      status: 'ok', platform, count: cookies.length,
      netscape: '# Netscape HTTP Cookie File\n# Generated by TokenScope Chrome Extension\n# Platform: ' + platform + '\n\n' + lines.join('\n'),
    };
  } catch (e) {
    return { status: 'error', platform, error: e.message };
  }
}

// ============ 推送到服务器 ============
async function pushToServer(platform, netscape) {
  const result = await apiWithTotp('POST', '/api/admin/credentials', {
    platform, credential_type: 'cookie', credential_data: netscape, note: 'Chrome Extension',
  });
  if (result.error) return { success: false, error: result.error };
  return { success: true };
}

// ============ 消息分发 ============
chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  switch (request.action) {

    case 'generate_totp':
      (async () => {
        let secret = request.secret;
        let keyName = request.keyName;
        if (!secret) {
          const stored = await chrome.storage.local.get(['totpSecret', 'totpKeyName']);
          secret = stored.totpSecret;
          keyName = stored.totpKeyName;
        }
        if (!secret) { sendResponse({ error: '未配置密钥' }); return; }
        try {
          const code = await generateTotp(secret);
          sendResponse({ code, keyName: keyName || 'default' });
        } catch (e) { sendResponse({ error: e.message }); }
      })();
      return true;

    case 'collect':
      collectPlatform(request.platform, request.domain).then(sendResponse);
      return true;

    case 'push':
      pushToServer(request.platform, request.netscape).then(sendResponse);
      return true;

    case 'count_cookies':
      chrome.cookies.getAll({ domain: request.domain }).then(c => sendResponse({ count: c.length })).catch(() => sendResponse({ count: 0 }));
      return true;

    case 'get_login_cred':
      chrome.storage.session.get('login_' + request.platform, d => sendResponse(d['login_' + request.platform] || null));
      return true;

    case 'clear_login_cred':
      chrome.storage.session.remove('login_' + request.platform, () => sendResponse({}));
      return true;

    default:
      sendResponse({ error: 'unknown action' });
  }
});
